language: node_js
sudo: false
dist: trusty
node_js: '10'
addons:
  firefox: latest
  chrome: stable
before_script:
- npm run bootstrap
- npm run lint
- npm run build
script:
- xvfb-run npm run test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test-sauce; fi
env:
  global:
  - secure: b0zzxp6sYm4OhFhOXeBppjUanBP2nM6Lx8y1b4Om3HvzhU9FEYhsPEybYzUQ2fEnEl31kAZ/4ppki0+9dAVoMAHaNAO0kH33wJezkFtJQqGe5BlQ01fj0Am+uC54XCBEmYDwHtacEtWhE3t+MM2mVpBy0n/ZvnuNla+CWBSWVfncl48uCBgaq4WiEDfJfXjTTsoSXXKSB77qRgB098ySsVtIMfS42zVolqJSsdFZ3FKIHXB7synVMDUHjGQuLUTKA1xY13ulnOuIZ5kbyFif/eM5r5Pq2WoqtJlRoIf59rH5D5ljguqt1EMLuS2eRx800doW9Oa8TV8DW+sAdDAY/0+y9Whua49vBulYjXlCp/Q7cKG8zKuWwKSAFMQLaLAFgwzEOfHCC0+E/TU63peOBtpY4gBy9ZG8fcK9ALIuMUDXrtweRx39rwtn8PQYwKvIULJx8BkNP1uAOMFFUKfdv9Uc0Xlgm15nAwBo7xw1jkNzVNUUgJMTLTMnKIosIbx9AaMTbnfQa0ixkS2fg6aq+/8LnM9lzNlbJsRC8ZhYZ9dRm3iecTUGlv8gcE+nfPaQR2Hv5x/4pEoTXFX1QAOD4Kc+XJBuy2ryYO8qmyQVW6IaVg2obqtKOlqEuFNe4O4mOG+MGvdqJOt26fOeBfB+4ysmuORU2NM+78fiY/rH40Y=
  - secure: UQw7lxDLHz+5VW5s/CSIeZjviNtBba8bLj26oeUKaeJyuVU4bW5JFhda2wt2zU0fUap4gv3rZQvLLFOhJqwNmIUuOm9P5cXiVNRRYBdmbIpWJATxYVmw+IMhbuo8ZkjhwbfwOwmEN/oDuhVaYe1zERtGCka8yv6O3GoEiH/A/VWmoSL6KW8zKkX2+LkTNYKWQUfqHT4qc6e/tXTynCYVXezZUess8eVyD4MFSVLAg085UBk3YjVyISDHKe4yIB9+25+cm/gc5VROZN9yMzuG48h94beD+YrcVOsDSWguLRn5CwkUWVpU7b8AnLAJW2+iyKHeelLchLpBJhoHsxiByd1W7mEk1e76hvHhci+EKPosbe/OmE5MFRB5ABJhIl8/+GGqQF1XYkxWN73fHW6v6xgDSov7nt1ibkxrHgONGvCkaHANT2LdszbKAM7zVmUaqrRyxbn2tMW95JykjJA8pftYmz0sH65T6LPHpGbIpjdRmNiaSleRydE0xlXWMV87OcJWras5PmBRb0kTsGi8CY9IQusrKaXem+dUh1tQGVxg7oZ+3b23Iv8S7/KRdI0LfrAeYEw+ZhaQWI5wIIKf5FrMARGOoTcxALSGtyFiJKebHuL/bfPxaYc2annbTQMpjsoPFTXGOPDGXEKo5xEB6SJ8l3vOYM5T8smjmabJnag=
